### ISSUE TITLE
Unpkg?

### ISSUE THREAD

**Issue by JAForbes** [StephanHoyer/tagl#9]
Pretty please? 🙏

**Comment by StephanHoyer** [comment]
[fixed](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEAHRDEMAcyhKFaLULi1Y+KLVUAKFeoCUWrZRBwYsasQj0EPAEyIAjAHY2HEEwcPHxqOAEaekZmHjYAXSooCDQAazdUQK48c3IqAFdpch4SYgk4RAB6Cry0CRTVUNosCpyAAS98DvcKuiwsenx+W2IATwluO2ppCAlRVjjWIA)
